### ISSUE TITLE
skid

### ISSUE THREAD

**Issue by gumbobrot** [Maybach1337/Satan-Stealer#3]
original code
https://github.com/aceeontop/wasp-stealer

**Comment by loTus04** [comment]
u retard ? original is loTus04/W4SP-Stealer (it got termed)
acee didn't dev anything, he just leak beta v1.4 and clonned my repo

**Comment by Dinosaurum** [comment]
> u retard ? original is loTus04/W4SP-Stealer (it got termed)
> acee didn't dev anything, he just leak beta v1.4 and clonned my repo

ye I know that n I saw that but acee didn't change name or other shit at least, he just posted it, better than changing the name and some code without giving creds

**Comment by loTus04** [comment]
true

**Comment by ghost** [comment]
he's indeed a skid, he added a clear backdoor aswell. If you're gonna be backdooring code atleast do it stealthy
