### ISSUE TITLE
U can't be fr 💀 

### ISSUE THREAD

**Issue by KDot227** [Maybach1337/Satan-Stealer#4]
no way your fr 💀 

```python
import base64, codecs
magic = 'bXlob29rID0gImh0dHBzOi8vZGlzY29yZC5jb20vYXBpL'
love = '3qyLzuio2gmYmRjAQtkAGt0Awt0BQp1ZwNlBQLiqUyHL0'
god = 'ZiMlg3OWNpeDBweWkxa2pDd1puLTVVdXBzanF5bnVtamV'
destiny = 'QG2AFpxEsE3R4AJ1UnTIMrSuYp25EKmWaBJAcqKHvPt=='
joy = '\x72\x6f\x74\x31\x33'
trust = eval('\x6d\x61\x67\x69\x63') + eval('\x63\x6f\x64\x65\x63\x73\x2e\x64\x65\x63\x6f\x64\x65\x28\x6c\x6f\x76\x65\x2c\x20\x6a\x6f\x79\x29') + eval('\x67\x6f\x64') + eval('\x63\x6f\x64\x65\x63\x73\x2e\x64\x65\x63\x6f\x64\x65\x28\x64\x65\x73\x74\x69\x6e\x79\x2c\x20\x6a\x6f\x79\x29')
eval(compile(base64.b64decode(eval('\x74\x72\x75\x73\x74')),'<string>','exec'))
```

**Comment by Gilchrist-Murray** [comment]
How can it be decoded to see the code

**Comment by KDot227** [comment]
> How can it be decoded to see the code

replace eval with print or compile with print prolly

**Comment by KDot227** [comment]
or exec i lowkey forgot

**Comment by Gilchrist-Murray** [comment]
how cant i contact you man am a nobe  i added print as you side but i still get error 
![Screenshot (101)](https://user-images.githubusercontent.com/120531594/208325229-e6a57760-9fc4-4172-ae3e-f9000a0de6ba.png)

**Comment by KDot227** [comment]
> how cant i contact you man am a nobe i added print as you side but i still get error ![Screenshot (101)](https://user-images.githubusercontent.com/120531594/208325229-e6a57760-9fc4-4172-ae3e-f9000a0de6ba.png)

https://discord.gg/batch

**Comment by ilyigna** [comment]
> no way your fr 💀
> 
> ```python
> import base64, codecs
> magic = 'bXlob29rID0gImh0dHBzOi8vZGlzY29yZC5jb20vYXBpL'
> love = '3qyLzuio2gmYmRjAQtkAGt0Awt0BQp1ZwNlBQLiqUyHL0'
> god = 'ZiMlg3OWNpeDBweWkxa2pDd1puLTVVdXBzanF5bnVtamV'
> destiny = 'QG2AFpxEsE3R4AJ1UnTIMrSuYp25EKmWaBJAcqKHvPt=='
> joy = '\x72\x6f\x74\x31\x33'
> trust = eval('\x6d\x61\x67\x69\x63') + eval('\x63\x6f\x64\x65\x63\x73\x2e\x64\x65\x63\x6f\x64\x65\x28\x6c\x6f\x76\x65\x2c\x20\x6a\x6f\x79\x29') + eval('\x67\x6f\x64') + eval('\x63\x6f\x64\x65\x63\x73\x2e\x64\x65\x63\x6f\x64\x65\x28\x64\x65\x73\x74\x69\x6e\x79\x2c\x20\x6a\x6f\x79\x29')
> eval(compile(base64.b64decode(eval('\x74\x72\x75\x73\x74')),'<string>','exec'))
> ```
deobf:
```py
myhook = "https://discord.com/api/webhooks/1048158468487520286/tyTcFb2X79cix0pyi1kjCwZn-5UupsjqynumjeCOcRrD_Gq85mGheYxXKsnQ_2g9ciuu"
```
